package com.epam.testapp.dao.constants;

public enum FieldName {

	NUM_OF_WORKERS, ADDRESS_ID, ADDRESS_NAME, CITY_ID, CITY_NAME, COUNTRY_ID, COUNTRY_NAME, COMPANY_ID, COMPANY_NAME, EMPLOYEE_ID, FIRST_NAME, LAST_NAME, WORKPLACE_ID, POSITION_ID, POSITION_NAME, OFFICE_ID, COUNT

}
